[game]
hostname = "🛰️ Corvax — Атара 🌌 [TTS]"
desc = "Корвакс первый русскоязычный проект в Space Station 14.\nНа этом сервере средние требования к RP.\n[Имеется интеграция TTS (Text-To-Speech)]"
map_pool = "CorvaxDefaultMapPool"
soft_max_players = 70
map_rotation = true

[net]
max_connections = 150

[rules]
time = 180.0

[queue]
enabled = true

[tts]
enabled = true

[discord_auth]
enabled = true

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e,tts"
