[game]
hostname = "🛰️ Corvax — Нова 🪐 [TTS]"
desc = "[Требуется 40 часов на другом сервере Corvax!]\nКорвакс первый русскоязычный проект в Space Station 14.\nНа этом сервере высокие требования к RP.\nИмеется интеграция TTS (Text-To-Speech)."
map_pool = "CorvaxDefaultMapPool"
soft_max_players = 60
map_rotation = false

[net]
max_connections = 120

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 0
min_overall_hours = 40

[rules]
time = 10.0

[queue]
enabled = true

[tts]
enabled = true

[discord_auth]
enabled = true

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e,tts"
